In [1]:
# COMPSCI 4ML3 Q2
# Tahseen Ahmed
# Saturday, February 6th, 2020
# ============================
import matplotlib.pyplot as plt
import numpy as np
import statsmodels.api as sm # 
from sklearn.linear_model import LinearRegression # Use this for MLR

In [2]:
# generate n data points based on a combination of sinosuidal and polynomial functions
def generate_data(n):
    X = np.random.rand(n, 3)
    # Sorting multi-dimensional data is non-trivial.
    Y = 2 + (2*X[0]) + (3*X[1]) + (4*X[2]) + (3 *X[0] * X[1]) - (5 * X[1] * X[2]) + (2 * X[0]**2 * X[2]**2)
    # Adding noise
    Y = Y + 0.1*np.random.randn(n,1)
    return X, Y

myX,myY = generate_data(25000)
regressor = LinearRegression()
regressor.fit(myX,myY)

# display coefficients, not sure about intercept, so I take the mean of the matrix.
print(regressor.coef_, regressor.intercept_.mean())

[[-4.37131668e-04  5.17751109e-05 -5.03716156e-04]
 [-4.37131668e-04  5.17751109e-05 -5.03716156e-04]
 [-4.37131668e-04  5.17751109e-05 -5.03716156e-04]] 5.8179021220451235
